# Generated by Django 3.1 on 2025-06-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name_plural': 'Product Gallery'},
        ),
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, upload_to='variation_images/'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('cuff', 'Cuff')], max_length=200),
        ),
    ]
