# Generated by Django 3.1 on 2025-06-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20250608_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('cuff', 'Cuff'), ('top_length', 'Top Length'), ('leg_opening', 'Leg Opening')], max_length=200),
        ),
    ]
