# Generated by Django 3.1 on 2025-06-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20250608_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
