# Generated by Django 3.1 on 2025-06-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_variation_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('cuff', 'Cuff'), ('top_length', 'Top Length'), ('leg_opening', 'Leg Opening'), ('fabric', 'Fabric'), ('top_fit', 'Top Fit')], max_length=200),
        ),
    ]
