# Generated by Django 3.1 on 2025-06-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20250609_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('cuff', 'Cuff'), ('top_length', 'Top Length'), ('leg_opening', 'Leg Opening'), ('fabric', 'Fabric'), ('top_fit', 'Top Fit'), ('embroidery', 'Embroidery')], max_length=200),
        ),
    ]
