# Generated by Django 3.1 on 2025-07-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250724_0058'),
        ('store', '0012_auto_20250612_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tailor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tailor'),
        ),
    ]
