# Generated by Django 3.1 on 2025-08-01 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tailor_brand_name'),
        ('store', '0013_product_tailor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, unique=True)),
                ('brand_image_logo', models.ImageField(upload_to='brand_logos/')),
                ('brand_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='accounts.tailor')),
            ],
        ),
    ]
