# Generated by Django 3.1 on 2025-08-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tailor',
        ),
    ]
