# Generated by Django 3.1 on 2025-10-25 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tailor_brand_name'),
        ('store', '0018_auto_20250801_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='accounts.tailor'),
        ),
    ]
