apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-frobarn
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-frobarn
  template:
    metadata:
      labels:
        app: prod-frobarn
    spec:
      containers:
      - name: prod-frobarn
        image: frobarn/kart:1.0
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_ENV
          value: "prod"
        - name: DJANGO_SETTINGS_MODULE
          value: "frobarnkart.settings.prod"