apiVersion: v1
kind: Service
metadata:
  name: prod-frobarn-svc
  namespace: prod
spec:
  selector:
    app: prod-frobarn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer