# Generated by Django 3.1 on 2025-07-24 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_tailor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('business_city', models.CharField(max_length=100)),
                ('business_state', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('business_phone_number', models.CharField(max_length=20)),
                ('maximum_capacity_per_week', models.PositiveIntegerField()),
                ('local_bank', models.CharField(max_length=100)),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
