# Generated by Django 3.1 on 2025-07-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250724_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='brand_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
