# Generated by Django 3.1 on 2025-10-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tailor_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tailor',
            old_name='email_address',
            new_name='business_email_address',
        ),
    ]
