apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-frobarn
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-frobarn
  template:
    metadata:
      labels:
        app: dev-frobarn
    spec:
      containers:
      - name: dev-frobarn
        image: frobarn/kart:1.0
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_ENV
          value: "dev"
        - name: DJANGO_SETTINGS_MODULE
          value: "frobarnkart.settings.dev"
        - name: ALLOWED_HOSTS
          value: "dev.frobarn.com"
        - name: DEBUG
          value: "True"
        volumeMounts:
        - name: staticfiles
          mountPath: /app/staticfiles
        - name: mediafiles
          mountPath: /app/media

        # Run collectstatic before starting Gunicorn
        command:
          - sh
          - -c
          - |
            python manage.py collectstatic --noinput &&
            gunicorn --bind 0.0.0.0:8000 frobarnkart.wsgi:application

      volumes:
      - name: staticfiles
        emptyDir: {}
      - name: mediafiles
        emptyDir: {}