apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-frobarn
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-frobarn
  template:
    metadata:
      labels:
        app: dev-frobarn
    spec:
      containers:
      - name: dev-frobarn
        image: frobarn/kart:1.1
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_ENV
          value: "dev"
        - name: DJANGO_SETTINGS_MODULE
          value: "frobarnapp.settings.dev"