apiVersion: v1
kind: Service
metadata:
  name: dev-frobarn-svc
  namespace: dev
spec:
  selector:
    app: dev-frobarn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer