# Generated by Django 3.1 on 2025-10-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('source', models.CharField(blank=True, default='popup', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='newslettercontact',
            index=models.Index(fields=['email'], name='utility_new_email_c268ff_idx'),
        ),
    ]
