# Generated by Django 3.1 on 2025-06-13 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20250302_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stomach', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trousers_waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thigh_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thigh_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('knee_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('knee_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('armhole_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('armhole_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bicep_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bicep_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wrist_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wrist_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('crotch', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('arm_length_to_wrist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('outside_leg_to_ground', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inseam_to_ground', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inseam_to_ankle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('straight_shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('curve_shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neck_to_chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neck_to_waist_front', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neck_to_waist_back', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neck_to_crotch_backlong', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neck_to_middle_hand_frontlong', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neck_to_knee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neck_high_to_knee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
