# Generated by Django 3.1 on 2025-06-13 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_usermeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeasurement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
