# Generated by Django 3.1 on 2025-07-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_usermeasurementdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeasurementdata',
            name='order_number',
            field=models.CharField(default='1970010101', max_length=20),
        ),
    ]
