# Generated by Django 3.1 on 2025-07-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_usermeasurementdata_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeasurementdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
